---
- name: Mettre à jour le cache des paquets (apt update)
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Installer les outils indispensables
  apt:
    name:
      - curl
      - git
      - vim
      - htop
    state: present

- name: S'assurer que le fuseau horaire est correct
  timezone:
    name: "Europe/Zurich"