[proxmox_vms]
dns.sureau.ch ansible_host=192.168.10.28
proxy.sureau.ch ansible_host=192.168.10.38
docker.sureau.ch ansible_host=192.168.10.39
drive.sureau.ch ansible_host=192.168.10.36
crm.sureau.ch ansible_host=192.168.10.31
auth.sureau.ch ansible_host=192.168.10.33
reverse-proxy.sureau.ch ansible_host=192.168.10.26
crm-oroboros.sureau.ch ansible_host=192.168.10.22
crm-phenomen.sureau.ch ansible_host=192.168.10.16
mon ansible_host=192.168.10.98

[all:vars]
ansible_user=ansible-user
ansible_ssh_private_key_file=./ansible-user
